link:
	ln BloomPattern.sc ~/.local/share/SuperCollider/Extensions/BloomPattern.sc
	ln BloomRecord.sc ~/.local/share/SuperCollider/Extensions/BloomRecord.sc
	ln BloomSample.sc ~/.local/share/SuperCollider/Extensions/BloomSample.sc
	ln BloomWildly.sc ~/.local/share/SuperCollider/Extensions/BloomWildly.sc